name: thesis
description: "Voice Voyage: Speech Sound Screening App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  intl: ^0.19.0
  firebase_core: ^4.5.0
  firebase_auth: ^6.2.0
  cloud_firestore: ^6.1.3
  audioplayers: ^6.6.0
  path_provider: ^2.1.5
  record: ^6.2.0
  http_parser: ^4.1.2
  provider: ^6.1.5+1
  flutter_svg: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core_platform_interface: ^6.0.2
  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/audio/screening/
    - assets/backgrounds/
    - assets/characters/
    - assets/fonts/
    - assets/icons/
    - assets/profiles/
    - assets/props/

  fonts:
    - family: Matemasie
      fonts:
        - asset: assets/fonts/Matemasie-Regular.ttf
    - family: Fredoka One
      fonts:
        - asset: assets/fonts/FredokaOne-Regular.ttf
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka.ttf
          weight: 300
        - asset: assets/fonts/Fredoka.ttf
          weight: 400
        - asset: assets/fonts/Fredoka.ttf
          weight: 500
        - asset: assets/fonts/Fredoka.ttf
          weight: 600
        - asset: assets/fonts/Fredoka.ttf
          weight: 700
