class GameAssetGroup {
  final String label;
  final List<String> assets;

  const GameAssetGroup(this.label, this.assets);
}

const gameAssetGroups = [
  GameAssetGroup('Shared', [
    'assets/game/shared/whale_idle.svg',
    'assets/game/shared/whale_happy.svg',
    'assets/game/shared/whale_listening.svg',
    'assets/game/shared/whale_encouraging.svg',
    'assets/game/shared/whale_thinking.svg',
    'assets/game/shared/whale_celebrating.svg',
    'assets/game/shared/whale_speaking.svg',
    'assets/game/shared/whale_retry.svg',
    'assets/game/shared/whale_holding_pearl.svg',
    'assets/game/shared/fish_blue.svg',
    'assets/game/shared/fish_yellow.svg',
    'assets/game/shared/turtle_receiver.svg',
    'assets/game/shared/octopus_receiver.svg',
    'assets/game/shared/success_badge_small.svg',
    'assets/game/shared/retry_prompt_visual.svg',
    'assets/game/shared/invalid_audio_wave.svg',
    'assets/game/shared/progress_pearl.svg',
    'assets/game/shared/level_complete_banner.svg',
    'assets/game/shared/next_target_transition.svg',
    'assets/game/shared/encouragement_heart.svg',
    'assets/game/shared/encouragement_star.svg',
    'assets/game/shared/processing_shell.svg',
  ]),
  GameAssetGroup('Words', [
    'assets/game/words/pig.svg',
    'assets/game/words/ball.svg',
    'assets/game/words/10.svg',
    'assets/game/words/dog.svg',
    'assets/game/words/key.svg',
    'assets/game/words/goat.svg',
  ]),
  GameAssetGroup('Bubble Bay', [
    'assets/game/bubble_bay/bubble_bay_background.png',
    'assets/game/bubble_bay/sound_bubble_idle.svg',
    'assets/game/bubble_bay/sound_bubble_partial.svg',
    'assets/game/bubble_bay/sound_bubble_full.svg',
    'assets/game/bubble_bay/bubble_pop_effect.svg',
    'assets/game/bubble_bay/coral_ring.svg',
    'assets/game/bubble_bay/glowing_pearl_off.svg',
    'assets/game/bubble_bay/glowing_pearl_on.svg',
    'assets/game/bubble_bay/pearl_slot.svg',
    'assets/game/bubble_bay/reef_decor.svg',
    'assets/game/bubble_bay/success_sparkle.svg',
    'assets/game/bubble_bay/retry_effect.svg',
    'assets/game/bubble_bay/invalid_audio_effect.svg',
    'assets/game/bubble_bay/instruction_panel_decor.svg',
  ]),
  GameAssetGroup('Coral Cargo', [
    'assets/game/coral_cargo/coral_cargo_background.png',
    'assets/game/coral_cargo/cargo_tube.svg',
    'assets/game/coral_cargo/cargo_box.svg',
    'assets/game/coral_cargo/target_item_frame.svg',
    'assets/game/coral_cargo/cargo_platform.svg',
    'assets/game/coral_cargo/delivery_hatch.svg',
    'assets/game/coral_cargo/receiver_turtle.svg',
    'assets/game/coral_cargo/receiver_octopus.svg',
    'assets/game/coral_cargo/success_delivery_effect.svg',
    'assets/game/coral_cargo/mix_up_effect.svg',
    'assets/game/coral_cargo/underwater_mail_props.svg',
    'assets/game/coral_cargo/retry_state.svg',
    'assets/game/coral_cargo/completed_delivery_effect.svg',
  ]),
  GameAssetGroup('Reef Route', [
    'assets/game/reef_route/reef_route_background.png',
    'assets/game/reef_route/reef_gate_closed.svg',
    'assets/game/reef_route/reef_gate_open.svg',
    'assets/game/reef_route/route_marker.svg',
    'assets/game/reef_route/route_path.svg',
    'assets/game/reef_route/fish_school.svg',
    'assets/game/reef_route/fish_swim_effect.svg',
    'assets/game/reef_route/gate_success_glow.svg',
    'assets/game/reef_route/paused_before_gate.svg',
    'assets/game/reef_route/route_sign.svg',
    'assets/game/reef_route/phrase_feedback.svg',
    'assets/game/reef_route/coral_checkpoint.svg',
  ]),
  GameAssetGroup("Captain's Call", [
    'assets/game/captains_call/captains_call_background.png',
    'assets/game/captains_call/submarine_main.svg',
    'assets/game/captains_call/command_panel.svg',
    'assets/game/captains_call/sonar_visual.svg',
    'assets/game/captains_call/sonar_ping_effect.svg',
    'assets/game/captains_call/rescue_arm.svg',
    'assets/game/captains_call/treasure_chest.svg',
    'assets/game/captains_call/underwater_gate.svg',
    'assets/game/captains_call/submarine_success_effect.svg',
    'assets/game/captains_call/treasure_sparkle.svg',
    'assets/game/captains_call/rescue_effect.svg',
    'assets/game/captains_call/fuzzy_sonar_retry.svg',
  ]),
];
