// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLNc9M1bO1_nY_Zejqp24hWhnDgZ4kfcQ',
    appId: '1:877785096323:web:d278fa649e2548bf48bbb6',
    messagingSenderId: '877785096323',
    projectId: 'thesis-d326c',
    authDomain: 'thesis-d326c.firebaseapp.com',
    storageBucket: 'thesis-d326c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl4BGjH7Is2el6PSZIkXOENepO83rZi3k',
    appId: '1:877785096323:android:99b72f63c025c88f48bbb6',
    messagingSenderId: '877785096323',
    projectId: 'thesis-d326c',
    storageBucket: 'thesis-d326c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmyw2wtpwBFoqKZ8MBuQtRDVomgN-SAvo',
    appId: '1:877785096323:ios:a82bd7f6ca064c9748bbb6',
    messagingSenderId: '877785096323',
    projectId: 'thesis-d326c',
    storageBucket: 'thesis-d326c.firebasestorage.app',
    iosBundleId: 'com.example.sampleCode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLNc9M1bO1_nY_Zejqp24hWhnDgZ4kfcQ',
    appId: '1:877785096323:web:ed038d57cf3746e348bbb6',
    messagingSenderId: '877785096323',
    projectId: 'thesis-d326c',
    authDomain: 'thesis-d326c.firebaseapp.com',
    storageBucket: 'thesis-d326c.firebasestorage.app',
  );
}
