// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2pjn_hhrtDEXTyfPvz7ZrMDLuUUhNGOE',
    appId: '1:998191263599:web:cf88cf4e1af2d53fc9029a',
    messagingSenderId: '998191263599',
    projectId: 'voice-voyage-thesis-2026',
    authDomain: 'voice-voyage-thesis-2026.firebaseapp.com',
    storageBucket: 'voice-voyage-thesis-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7W0PsUBHX6JsGYMXxL1l5g6kLn1CUM3Q',
    appId: '1:998191263599:android:3eb1969412394e0dc9029a',
    messagingSenderId: '998191263599',
    projectId: 'voice-voyage-thesis-2026',
    storageBucket: 'voice-voyage-thesis-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhWKoYkZz5YrSH6Rkuk7adhMLrKGO-_bA',
    appId: '1:998191263599:ios:bfab31cae8338a76c9029a',
    messagingSenderId: '998191263599',
    projectId: 'voice-voyage-thesis-2026',
    storageBucket: 'voice-voyage-thesis-2026.firebasestorage.app',
    iosBundleId: 'com.example.sampleCode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2pjn_hhrtDEXTyfPvz7ZrMDLuUUhNGOE',
    appId: '1:998191263599:web:20f9163ad27910aec9029a',
    messagingSenderId: '998191263599',
    projectId: 'voice-voyage-thesis-2026',
    authDomain: 'voice-voyage-thesis-2026.firebaseapp.com',
    storageBucket: 'voice-voyage-thesis-2026.firebasestorage.app',
  );
}
